name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install NPM packages
        run: npm install

      - name: Install Eslint
      - run: npm install eslint

      - name: run Eslint
        run: npx eslint src

      - name: Build project
        run: npm run build

      - name: Run tests and produce reports
        run: npm run test
